### PR TITLE
Fixes to build on musl

### PR DESCRIPTION
**Pull request by kraj**

### CODE REVIEW

**Comment by pavlix** [comment]
Hello. I've just made simiar changes locally. What distro are you building for? Also please note the “submitting patches“ section in the README. The author, @jpirko, is a kernel developer. They tend to have unusual expectations regarding change submission.

I am building for OpenWRT.

**Comment by kraj** [comment]
@pavlix thanks, this is for yocto when built with musl C library, I have now sent it to the mailing list as well ( hopefully the ml wont need me to be a subscriber to post patches )

**Comment by jpirko** [comment]
Please send me the patch. See file "SubmittingPatches". Thanks!

**Comment by pavlix** [comment]
I submitted my own musl compat patch as mentioned in SubmittingPatches but it never appeared in https://lists.fedorahosted.org/archives/list/libteam@lists.fedorahosted.org/ – that makes me ask… Does the mailing list actually work? @jpirko @kraj

**Comment by jpirko** [comment]
> I submitted my own musl compat patch as mentioned in SubmittingPatches but it never appeared in https://lists.fedorahosted.org/archives/list/libteam@lists.fedorahosted.org/ – that makes me ask… Does the mailing list actually work? @jpirko @kraj

It's there, I applied & pushed it.

**Pull request closed without merging**
